#!/usr/bin/env bash

set -eu

cd "$(dirname "$0")/.."

function clone_repo {
	owner=$1
	name=$2
	sha=$3

	path=examples/$name
	if [ ! -d "$path" ]; then
		echo "Cloning $owner/$name"
		git clone "https://github.com/$owner/$name" "$path"
	fi

	pushd "$path" >/dev/null
	actual_sha=$(git rev-parse HEAD)
	if [ "$actual_sha" != "$sha" ]; then
		echo "Updating $owner/$name to $sha"
		git fetch
		git reset --hard "$sha"
	fi
	popd >/dev/null
}

clone_repo bazelbuild starlark 32993fa0d1f1e4f3af167d249be95885ba5014ad
clone_repo mcuadros ascode ca95f0f93cf4a25f08bd9b961b2042efbca72a9d
clone_repo cruise-automation isopod 9e70e4f706c16c8d354ca00b26220330bcaabfec

known_failures="$(cat script/known_failures.txt)"

# shellcheck disable=2046
tree-sitter parse -q \
	"examples/**/BUILD" "examples/**/WORKSPACE" "examples/**/*.bzl" "examples/**/*.star" "examples/**/*.ipd" \
	$(for failure in $known_failures; do echo "!${failure}"; done)

example_count=$(find examples -name "BUILD" -o -name "WORKSPACE" -o -name "*.bzl" -o -name "*.star" -o -name "*.ipd" | wc -l)
failure_count=$(wc -w <<<"$known_failures")
success_count=$((example_count - failure_count))
success_percent=$(bc -l <<<"100*${success_count}/${example_count}")

printf \
	"Successfully parsed %d of %d example files (%.1f%%)\n" \
	"$success_count" "$example_count" "$success_percent"
